"""Encoding of one information set for distributed workers."""

from collections.abc import Sequence

from frame_codes.coding_scheme.codes.code_family import CodeFamily
from frame_codes.coding_scheme.state_utils.encoded_information import EncodedInformation


class Encoder:
    """Assign code-weighted information to identified workers."""

    @staticmethod
    def encode(
        information_set: Sequence,
        code_family: CodeFamily,
    ) -> list[EncodedInformation]:
        """Create the encoded inputs for every worker in a generated code.

        Args:
            information_set: Information items in the order represented by the
                code matrix columns. Items may be arbitrary objects.
            code_family: Family containing a generated code.

        Returns:
            One encoded-information record for every required worker.

        Raises:
            AttributeError: If no code has been generated by `code_family`.
            ValueError: If the information count or worker layout is invalid.
        """
        worker_count = code_family.number_of_workers_required()
        return [
            EncodedInformation(information_id=worker_id,
                               information=code_family.encode_for_worker(worker_id, information_set))
            for worker_id in range(worker_count)
        ]
